### ISSUE TITLE
switchFrame

### ISSUE THREAD

**Issue by Simn** [nadako/vshaxe-eval-debug#4]
From @ericbishton at https://github.com/vshaxe/eval-debugger/wiki/Debugger-Protocol:

> I'm not sure why the debug server needs to track this state. The GUI/CLI can keep track of this by itself. If a particular stack frame is needed in order to inspect variables, then I would expect that frame ID to be included in the "evaluate expression" command. Oh, yeah. We need one of those, too.

His remark makes sense to me. Why not pass the frame ID to the relevant commands directly? What's your opinion @nadako?

**Comment by nadako** [comment]
I think that's just how eval debugger was implemented initially, and to support that in the protocol I made that `maybeSwitchFrame` function. It would be nice to be able to pass the id directly of course. That means moving parts of the current code from the client into the compiler (like assigning unique ids for references), but I'm all for it!

**Comment by Simn** [comment]
Right, references, I forgot about that... That makes me not want to do it because I still don't know how this works.

**Comment by Simn** [comment]
This is obsolete.
